version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: au.com.dius.pact
    versions:
    - 4.1.15
    - 4.1.16
    - 4.1.17
    - 4.2.0
    - 4.2.1
    - 4.2.2
    - 4.2.3
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-core
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-websocket
    versions:
    - 10.0.0
    - 10.0.2
    - 10.0.4
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: org.sonarqube
    versions:
    - 3.1.1
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.2
  - dependency-name: io.spring.dependency-management
    versions:
    - 1.0.11.RELEASE
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1-jre
