---
version: '2.1'

services:
  pdf-service-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/cmc/pdf-service-api
    environment:
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
    volumes:
      - ./build/install/pdf-service:/opt/app/
    ports:
      - 5500:5500
