spring:
  application:
    name: "pdf-service"

server:
  port: 5500

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      show-details: always
