apiVersion: v2
name: rpe-pdf-service
home: https://github.com/hmcts/rpe-pdf-service
version: 0.5.0
description: PDF generation service
maintainers:
  - name: HMCTS Platform engineering team
dependencies:
  - name: java
    version: ~2.18.0
    repository: '@hmctspublic'
